MIGRATION_STATUS_RUNNING = "RUNNING"
MIGRATION_STATUS_COMPLETED = "COMPLETED"
MIGRATION_STATUS_ERROR = "ERROR"

TASK_STATUS_PENDING = "PENDING"
TASK_STATUS_RUNNING = "RUNNING"
TASK_STATUS_COMPLETED = "COMPLETED"
TASK_STATUS_ERROR = "ERROR"
TASK_STATUS_CANCELED = "CANCELED"

TASK_TYPE_EXPORT_INSTANCE = "EXPORT_INSTANCE"
TASK_TYPE_IMPORT_INSTANCE = "IMPORT_INSTANCE"

TASK_EVENT_INFO = "INFO"
TASK_EVENT_WARNING = "WARNING"
TASK_EVENT_ERROR = "ERROR"
